site_name: DDLCheck
site_description: CLI tool to analyze SQL migrations for potential production database risks
site_author: Oliver Rice

repo_url: https://github.com/olirice/ddlcheck
repo_name: olirice/ddlcheck

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "pymdownx.superfences.fence_code_format"
        - name: terminal
          class: terminal
          format: "pymdownx.superfences.fence_code_format"
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Checks:
    - Overview: checks/index.md
    - Add Column: checks/add_column.md
    - Alter Column Type: checks/alter_column_type.md
    - Drop Column: checks/drop_column.md
    - Create Index: checks/create_index.md
    - Rename Column: checks/rename_column.md
    - Set Not Null: checks/set_not_null.md
    - Update Without Filter: checks/update_without_filter.md
    - Drop Table: checks/drop_table.md
    - Truncate: checks/truncate.md
  - Custom Checks: custom_checks.md
  - Development: development.md
